apiVersion: v1
kind: Service
metadata:
  name: champions-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: champions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: images-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: matches-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: matches
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: players-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: players
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000