apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.champions.name }}
  namespace: {{ .Values.champions.namespace }}
  labels:
    app: {{ .Values.champions.name }}
spec:
  replicas: {{ .Values.champions.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.champions.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.champions.name }}
    spec:
      containers:
        - name: {{ .Values.champions.name }}-container
          image: {{ .Values.champions.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.champions.port }}
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.username | quote }}
                  optional: false 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.password | quote }}
                  optional: false 
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.host | quote }}
                  optional: false 
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.db | quote }}
                  optional: false 
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.port | quote }}
                  optional: false 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.name }}
  namespace: {{ .Values.images.namespace }}
  labels:
    app: {{ .Values.images.name }}
spec:
  replicas: {{ .Values.images.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.images.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.name }}
    spec:
      containers:
        - name: {{ .Values.images.name }}-container
          image: {{ .Values.images.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.images.port }}
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.username | quote }}
                  optional: false 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.password | quote }}
                  optional: false 
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.host | quote }}
                  optional: false 
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.db | quote }}
                  optional: false 
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.port | quote }}
                  optional: false 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.matches.name }}
  namespace: {{ .Values.matches.namespace }}
  labels:
    app: {{ .Values.matches.name }}
spec:
  replicas: {{ .Values.matches.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.matches.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.matches.name }}
    spec:
      containers:
        - name: {{ .Values.matches.name }}-container
          image: {{ .Values.matches.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.matches.port }}
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.username | quote }}
                  optional: false 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.password | quote }}
                  optional: false 
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.host | quote }}
                  optional: false 
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.db | quote }}
                  optional: false 
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.port | quote }}
                  optional: false 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.players.name }}
  namespace: {{ .Values.players.namespace }}
  labels:
    app: {{ .Values.players.name }}
spec:
  replicas: {{ .Values.players.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.players.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.players.name }}
    spec:
      containers:
        - name: {{ .Values.players.name }}-container
          image: {{ .Values.players.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.players.port }}
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.username | quote }}
                  optional: false 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.password | quote }}
                  optional: false 
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.host | quote }}
                  optional: false 
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.db | quote }}
                  optional: false 
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ $.Values.global.mysql.port | quote }}
                  optional: false 