apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong-class
  annotations:
{{ toYaml .Values.gatewayclass.annotations | indent 4 }}
spec:
  controllerName: konghq.com/kic-gateway-controller