apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gatewayclass.name }}
  listeners:
  - name: kong-listeners
    port: {{ .Values.gateway.port }}
    protocol: {{ .Values.gateway.protocol }}
    allowedRoutes:
      namespaces:
        from: {{ .Values.gateway.from }}