apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.type }}
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc}}
  host: {{ .Values.host | b64enc }}
  db: {{ .Values.db | b64enc }}
  port: {{ .Values.port | b64enc }}