apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.champions.name }}-svc
  namespace: {{ .Values.champions.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.champions.name }}
  ports:
    - protocol: {{ .Values.championsservice.protocol }}
      port: {{ .Values.championsservice.port }}
      targetPort: {{ .Values.champions.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.images.name }}-svc
  namespace: {{ .Values.images.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.images.name }}
  ports:
    - protocol: {{ .Values.imagesservice.protocol }}
      port: {{ .Values.imagesservice.port }}
      targetPort: {{ .Values.images.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.matches.name }}-svc
  namespace: {{ .Values.matches.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.matches.name }}
  ports:
    - protocol: {{ .Values.matchesservice.protocol }}
      port: {{ .Values.matchesservice.port }}
      targetPort: {{ .Values.matches.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.players.name }}-svc
  namespace: {{ .Values.players.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.players.name }}
  ports:
    - protocol: {{ .Values.playersservice.protocol }}
      port: {{ .Values.playersservice.port }}
      targetPort: {{ .Values.players.port }}